version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports: 
      - "8080:8080"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=devpassword
    depends_on:
      - db


  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=devdb
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data:
